/** Layout of a maze */
export interface MazeMap {
    rows: Array< Array<number> >;
    startX: number,
    startY: number,
    startD: number,
    name: string,
    id:string,
    symbol:string
}

/** Used to pass a collection of Maze IDs around */
export interface MazeIds{
    [key: string]:boolean
}

/** A state of the agent */
export interface State {
    s1:number,
    s2:number,
    s3:number,
    s4:number,
    d:number //Direction agent is pointing
    [key: string]: number | undefined
}

/** Maps a state transition of the agent (movement or direction change,
    defined using a string key to the arrays of states that occur after agent has moved. */
export interface StateTransitionMap {
    [key: string]: Array<State>
}


/** Measurement */
export interface IMeasure {
    predMatch: number, //Match between prediction and what actually happened.
    predCompress: number,//Compressibility of the prediction
    maxMatch: number, //Maximum possible match between prediction and what actually happened.
    actualCompress: number//Compressibility of the actual state
}

/**
 * Each entry records the distance between an agent's prediction and reality.
 * First key is the time stamp,
 *  Second key is the ID of the maze
 *  third the location or direction of the measurement.
 * */
export interface IMeasureStore {
    [key: string] : {//Time stamp
        [key: string]://Maze ID
            IMeasure[]
    }
}

/** Holds CI data per maze in a form suitable for plotting
 * [key: string] - Maze ID
 * x, y - values for plot
 */
export interface IMeasurePlot {
    [key: string] : {//Maze ID
        x:number[],
        y:number[]
    }
}

/** Maps sensor state of the agent, defined using a string key
    to the the probability distribution of states that occur after agent has moved. */
export interface StateProbMap {
    [key: string]: StateDist
}

/** Maps position and direction of agent (x, y, d) to a number coresponding to the PI
 * of an agent who makes a move from this position and direction.
  */
export interface PIMap {
    [key:string]: number
}

/** Probability distributions associated with each of the agent's sensors */
export interface StateDist{
    s1: {e:number, w:number, r:number},
    s2: {e:number, w:number, r:number},
    s3: {e:number, w:number, r:number},
    s4: {e:number, w:number, r:number},
    [key: string]: {e:number, w:number, r:number}
}

/* Probability distribution */
export interface ProbDist {
    [index: string]: number
}

/** Event generated by a Plotly graph */
export interface PlotlyEvent{
    points:Array<{x:number}>
}

/** Controls the display of legends for the prediction match plot */
export interface MazeLegends {
    [key:string]: {
        show:boolean,
        color:string,
        title:string,
        symbol:string
    }
}
